version: '3.1'
services:
  mongo:
    container_name: mongo
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=example
      - MONGODB_DATABASE=url_shortener
    restart: always
    volumes:
      - ./mongodb_data:/bitnami
  web:
    container_name: urlshortener
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - LPN_MONGO_HOST='http://3dsshorturl.opcellent.com'
      - LPN_MONGO_USER=root
      - LPN_MONGO_PASS=example
      - LPN_MONGO_DB=url_shortener
    depends_on:
      - mongo
