web:
  container_name: urlshortener
  build: ./web
  environment:
    - VIRTUAL_HOST=3dsshorturl.opcellent.com
    - LETSENCRYPT_HOST=3dsshorturl.opcellent.com
    - LETSENCRYPT_EMAIL=aukkwat@opcellent.com
    - VIRTUAL_PORT=3000
    - LPN_WEB_HOST=https://3dsshorturl.opcellent.com/
    - LPN_MONGO_HOST=172.31.14.165
    - LPN_MONGO_PORT=27017
    - LPN_MONGO_USER=root
    - LPN_MONGO_PASS=example
    - LPN_MONGO_DB=url_shortener
